---
title: "Network_Stats"
author: "Kathryn Atherton"
date: "2024-10-13"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
```

```{r load data}
metrics <- read.csv("/projectnb/talbot-lab-data/Katies_data/Street_Trees/Analysis/Networks/Results/network_metrics_plot.csv")
metrics <- metrics[-which(metrics$Plot == "X"),]
metrics$Tree_Type <- factor(metrics$Tree_Type, levels = c("Street Tree", "Urban Edge", "Urban Interior", "Rural Edge", "Rural Interior"))
metrics$N_samples <- c(rep(8,4),7,9,8,9,9,8,8,7,7,11,9,9,8,9,8,8,12,9,7,9,16,7,13,7,16,7,10,8,7,9,9,8,7,9,8,17,7,14,9,12,10)
metrics$Nodes <- round(metrics$Edges/metrics$Complexity)
```

```{r leaf}
ggplot(metrics[which(metrics$Sample_Type == "Leaf"),], aes(x = Tree_Type, y = Density)) + geom_boxplot()
ggplot(metrics[which(metrics$Sample_Type == "Leaf"),], aes(x = Tree_Type, y = Complexity)) + geom_boxplot()
ggplot(metrics[which(metrics$Sample_Type == "Leaf"),], aes(x = Tree_Type, y = Transitivity)) + geom_boxplot()
ggplot(metrics[which(metrics$Sample_Type == "Leaf"),], aes(x = Tree_Type, y = plantpath_betweenness)) + geom_boxplot()
ggplot(metrics[which(metrics$Sample_Type == "Leaf"),], aes(x = Tree_Type, y = plantpath_degree)) + geom_boxplot()
ggplot(metrics[which(metrics$Sample_Type == "Leaf"),], aes(x = Tree_Type, y = animalpath_betweenness)) + geom_boxplot()
ggplot(metrics[which(metrics$Sample_Type == "Leaf"),], aes(x = Tree_Type, y = animalpath_degree)) + geom_boxplot()
ggplot(metrics[which(metrics$Sample_Type == "Leaf"),], aes(x = Tree_Type, y = epiphyte_betweenness)) + geom_boxplot()
ggplot(metrics[which(metrics$Sample_Type == "Leaf"),], aes(x = Tree_Type, y = epiphyte_degree)) + geom_boxplot()
ggplot(metrics[which(metrics$Sample_Type == "Leaf"),], aes(x = Tree_Type, y = endophyte_betweenness)) + geom_boxplot()
ggplot(metrics[which(metrics$Sample_Type == "Leaf"),], aes(x = Tree_Type, y = endophyte_degree)) + geom_boxplot()

TukeyHSD(aov(Density ~ Tree_Type, metrics[which(metrics$Sample_Type == "Leaf"),]))
TukeyHSD(aov(Complexity ~ Tree_Type, metrics[which(metrics$Sample_Type == "Leaf"),]))
TukeyHSD(aov(Transitivity ~ Tree_Type, metrics[which(metrics$Sample_Type == "Leaf"),]))
TukeyHSD(aov(plantpath_betweenness ~ Tree_Type, metrics[which(metrics$Sample_Type == "Leaf"),]))
TukeyHSD(aov(plantpath_degree ~ Tree_Type, metrics[which(metrics$Sample_Type == "Leaf"),]))
TukeyHSD(aov(animalpath_betweenness ~ Tree_Type, metrics[which(metrics$Sample_Type == "Leaf"),]))
TukeyHSD(aov(animalpath_degree ~ Tree_Type, metrics[which(metrics$Sample_Type == "Leaf"),]))
TukeyHSD(aov(epiphyte_betweenness ~ Tree_Type, metrics[which(metrics$Sample_Type == "Leaf"),]))
TukeyHSD(aov(epiphyte_degree ~ Tree_Type, metrics[which(metrics$Sample_Type == "Leaf"),]))
TukeyHSD(aov(endophyte_betweenness ~ Tree_Type, metrics[which(metrics$Sample_Type == "Leaf"),]))
TukeyHSD(aov(endophyte_degree ~ Tree_Type, metrics[which(metrics$Sample_Type == "Leaf"),]))
```

```{r Soil, 0-15 cm}
ggplot(metrics[which(metrics$Sample_Type == "Soil, 0-15 cm" & metrics$N_samples < 13),], aes(x = Tree_Type, y = Density)) + geom_boxplot()
ggplot(metrics[which(metrics$Sample_Type == "Soil, 0-15 cm" & metrics$N_samples < 13),], aes(x = Tree_Type, y = Complexity)) + geom_boxplot()
ggplot(metrics[which(metrics$Sample_Type == "Soil, 0-15 cm" & metrics$N_samples < 13),], aes(x = Tree_Type, y = Transitivity)) + geom_boxplot()
ggplot(metrics[which(metrics$Sample_Type == "Soil, 0-15 cm" & metrics$N_samples < 13),], aes(x = Tree_Type, y = plantpath_betweenness)) + geom_boxplot()
ggplot(metrics[which(metrics$Sample_Type == "Soil, 0-15 cm" & metrics$N_samples < 13),], aes(x = Tree_Type, y = plantpath_degree)) + geom_boxplot()
ggplot(metrics[which(metrics$Sample_Type == "Soil, 0-15 cm" & metrics$N_samples < 13),], aes(x = Tree_Type, y = animalpath_betweenness)) + geom_boxplot()
ggplot(metrics[which(metrics$Sample_Type == "Soil, 0-15 cm" & metrics$N_samples < 13),], aes(x = Tree_Type, y = animalpath_degree)) + geom_boxplot()
ggplot(metrics[which(metrics$Sample_Type == "Soil, 0-15 cm" & metrics$N_samples < 13),], aes(x = Tree_Type, y = ECM_betweenness)) + geom_boxplot()
ggplot(metrics[which(metrics$Sample_Type == "Soil, 0-15 cm" & metrics$N_samples < 13),], aes(x = Tree_Type, y = ECM_degree)) + geom_boxplot()
ggplot(metrics[which(metrics$Sample_Type == "Soil, 0-15 cm" & metrics$N_samples < 13),], aes(x = Tree_Type, y = sap_betweenness)) + geom_boxplot()
ggplot(metrics[which(metrics$Sample_Type == "Soil, 0-15 cm" & metrics$N_samples < 13),], aes(x = Tree_Type, y = sap_degree)) + geom_boxplot()

TukeyHSD(aov(Density ~ Tree_Type, metrics[which(metrics$Sample_Type == "Soil, 0-15 cm" & metrics$N_samples < 13),]))
TukeyHSD(aov(Complexity ~ Tree_Type, metrics[which(metrics$Sample_Type == "Soil, 0-15 cm" & metrics$N_samples < 13),]))
TukeyHSD(aov(Transitivity ~ Tree_Type, metrics[which(metrics$Sample_Type == "Soil, 0-15 cm" & metrics$N_samples < 13),]))
TukeyHSD(aov(plantpath_betweenness ~ Tree_Type, metrics[which(metrics$Sample_Type == "Soil, 0-15 cm" & metrics$N_samples < 13),]))
TukeyHSD(aov(plantpath_degree ~ Tree_Type, metrics[which(metrics$Sample_Type == "Soil, 0-15 cm" & metrics$N_samples < 13),]))
TukeyHSD(aov(animalpath_betweenness ~ Tree_Type, metrics[which(metrics$Sample_Type == "Soil, 0-15 cm" & metrics$N_samples < 13),]))
TukeyHSD(aov(animalpath_degree ~ Tree_Type, metrics[which(metrics$Sample_Type == "Soil, 0-15 cm" & metrics$N_samples < 13),]))
TukeyHSD(aov(ECM_betweenness ~ Tree_Type, metrics[which(metrics$Sample_Type == "Soil, 0-15 cm" & metrics$N_samples < 13),]))
TukeyHSD(aov(ECM_degree ~ Tree_Type, metrics[which(metrics$Sample_Type == "Soil, 0-15 cm" & metrics$N_samples < 13),]))
TukeyHSD(aov(sap_betweenness ~ Tree_Type, metrics[which(metrics$Sample_Type == "Soil, 0-15 cm" & metrics$N_samples < 13),]))
TukeyHSD(aov(sap_degree ~ Tree_Type, metrics[which(metrics$Sample_Type == "Soil, 0-15 cm" & metrics$N_samples < 13),]))
```

```{r Soil, 15-30 cm}
ggplot(metrics[which(metrics$Sample_Type == "Soil, 15-30 cm" & metrics$N_samples < 13),], aes(x = Tree_Type, y = Density)) + geom_boxplot()
ggplot(metrics[which(metrics$Sample_Type == "Soil, 15-30 cm" & metrics$N_samples < 13),], aes(x = Tree_Type, y = Complexity)) + geom_boxplot()
ggplot(metrics[which(metrics$Sample_Type == "Soil, 15-30 cm" & metrics$N_samples < 13),], aes(x = Tree_Type, y = Transitivity)) + geom_boxplot()
ggplot(metrics[which(metrics$Sample_Type == "Soil, 15-30 cm" & metrics$N_samples < 13),], aes(x = Tree_Type, y = plantpath_betweenness)) + geom_boxplot()
ggplot(metrics[which(metrics$Sample_Type == "Soil, 15-30 cm" & metrics$N_samples < 13),], aes(x = Tree_Type, y = plantpath_degree)) + geom_boxplot()
ggplot(metrics[which(metrics$Sample_Type == "Soil, 15-30 cm" & metrics$N_samples < 13),], aes(x = Tree_Type, y = animalpath_betweenness)) + geom_boxplot()
ggplot(metrics[which(metrics$Sample_Type == "Soil, 15-30 cm" & metrics$N_samples < 13),], aes(x = Tree_Type, y = animalpath_degree)) + geom_boxplot()
ggplot(metrics[which(metrics$Sample_Type == "Soil, 15-30 cm" & metrics$N_samples < 13),], aes(x = Tree_Type, y = ECM_betweenness)) + geom_boxplot()
ggplot(metrics[which(metrics$Sample_Type == "Soil, 15-30 cm" & metrics$N_samples < 13),], aes(x = Tree_Type, y = ECM_degree)) + geom_boxplot()
ggplot(metrics[which(metrics$Sample_Type == "Soil, 15-30 cm" & metrics$N_samples < 13),], aes(x = Tree_Type, y = sap_betweenness)) + geom_boxplot()
ggplot(metrics[which(metrics$Sample_Type == "Soil, 15-30 cm" & metrics$N_samples < 13),], aes(x = Tree_Type, y = sap_degree)) + geom_boxplot()

TukeyHSD(aov(Density ~ Tree_Type, metrics[which(metrics$Sample_Type == "Soil, 15-30 cm" & metrics$N_samples < 13),]))
TukeyHSD(aov(Complexity ~ Tree_Type, metrics[which(metrics$Sample_Type == "Soil, 15-30 cm" & metrics$N_samples < 13),]))
TukeyHSD(aov(Transitivity ~ Tree_Type, metrics[which(metrics$Sample_Type == "Soil, 15-30 cm" & metrics$N_samples < 13),]))
TukeyHSD(aov(plantpath_betweenness ~ Tree_Type, metrics[which(metrics$Sample_Type == "Soil, 15-30 cm" & metrics$N_samples < 13),]))
TukeyHSD(aov(plantpath_degree ~ Tree_Type, metrics[which(metrics$Sample_Type == "Soil, 15-30 cm" & metrics$N_samples < 13),]))
TukeyHSD(aov(animalpath_betweenness ~ Tree_Type, metrics[which(metrics$Sample_Type == "Soil, 15-30 cm" & metrics$N_samples < 13),]))
TukeyHSD(aov(animalpath_degree ~ Tree_Type, metrics[which(metrics$Sample_Type == "Soil, 15-30 cm" & metrics$N_samples < 13),]))
TukeyHSD(aov(ECM_betweenness ~ Tree_Type, metrics[which(metrics$Sample_Type == "Soil, 15-30 cm" & metrics$N_samples < 13),]))
TukeyHSD(aov(ECM_degree ~ Tree_Type, metrics[which(metrics$Sample_Type == "Soil, 15-30 cm" & metrics$N_samples < 13),]))
TukeyHSD(aov(sap_betweenness ~ Tree_Type, metrics[which(metrics$Sample_Type == "Soil, 15-30 cm" & metrics$N_samples < 13),]))
TukeyHSD(aov(sap_degree ~ Tree_Type, metrics[which(metrics$Sample_Type == "Soil, 15-30 cm" & metrics$N_samples < 13),]))
```